### ISSUE TITLE
Sercure?

### ISSUE THREAD

**Issue by ImInTheICU** [CSM-BlueRed/Impostor#6]
How secure is it?
It looks to be simple B64 and Marshal....

**Comment by CSM-BlueRed** [comment]
its more than just this read the code

**Comment by ImInTheICU** [comment]
> its more than just this read the code

👍 
Im also working on changing the way you marshal code, by using xdis.
So you can compile(obfuscate) code in 3.8 and run it in 3.10

Or compile in 3.x.x
and run in 3.x.x +  or -

**Comment by CSM-BlueRed** [comment]
good! thanks
